[package]
name = "ingest"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
libc.workspace = true
media-model = { path = "../media-model" }
media-index = { path = "../media-index" }
serde.workspace = true
storage = { path = "../storage" }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
