//! Deterministic generated-data benchmark for Delivery Brain planning and local verified-copy
//! mechanics. It never opens a CaptureOS catalog, customer source, model, or network service.

#![forbid(unsafe_code)]

use delivery_brain::{
    build_manifest, DeliveryAssetCandidate, DeliverySourceCandidate, FilenameStrategy,
    ManifestBuildInput, OrganizationStrategy, ProductionPlanType, SelectionRules,
};
use ingest::{copy_and_verify, CopyVerificationOutcome};
use serde::Serialize;
use std::{env, fs, time::Instant};

const SCALES: [usize; 5] = [100, 1_000, 10_000, 50_000, 100_000];

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct Report {
    suite: String,
    benchmark_kind: &'static str,
    fixture: Fixture,
    scales: Vec<Scale>,
    verified_copy: CopyMeasurement,
    caveats: Vec<&'static str>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    version: &'static str,
    source: &'static str,
    contains_customer_media: bool,
    contains_network_calls: bool,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct Scale {
    record_count: usize,
    generated_selection_count: u64,
    planning_elapsed_us: u128,
    estimated_input_lower_bound_bytes: usize,
    manifest_checksum_stable: bool,
    unique_destination_paths: bool,
    collision_detection_elapsed_us: u128,
    resume_lookup_elapsed_us: u128,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct CopyMeasurement {
    generated_source_bytes: usize,
    initial_copy_verified: bool,
    rerun_reused_existing_verified_copy: bool,
}

fn main() {
    let suite = parse_suite();
    let scales = SCALES.into_iter().map(measure_scale).collect();
    let report = Report {
        suite,
        benchmark_kind: "deterministic generated Delivery Brain manifest and local verified-copy mechanics",
        fixture: Fixture {
            version: "captureos-delivery-brain.synthetic.v1",
            source: "in-memory manifest records plus temporary generated bytes; no catalog or customer media",
            contains_customer_media: false,
            contains_network_calls: false,
        },
        scales,
        verified_copy: measure_copy(),
        caveats: vec![
            "Manifest timing measures generated local data, not a claim about customer catalogs or filesystem latency.",
            "The bounded copy fixture verifies the product ingest primitive with generated bytes; it is not a throughput claim for a specific drive.",
            "No CaptureOS database, photo, preview, model, embedding, note, path from a customer catalog, or network service is opened.",
        ],
    };
    println!(
        "{}",
        serde_json::to_string_pretty(&report).expect("report serializes")
    );
}

fn parse_suite() -> String {
    let mut arguments = env::args().skip(1);
    match (arguments.next().as_deref(), arguments.next()) {
        (Some("--suite"), Some(value)) if value == "baseline" => value,
        _ => panic!("usage: delivery-brain-bench --suite baseline"),
    }
}

fn measure_scale(count: usize) -> Scale {
    let input = input(count);
    let estimate = input.assets.len() * std::mem::size_of::<DeliveryAssetCandidate>();
    let start = Instant::now();
    let first = build_manifest(&input).expect("generated fixture valid");
    let planning_elapsed_us = start.elapsed().as_micros();
    let collision_start = Instant::now();
    let unique_destination_paths = first
        .entries
        .iter()
        .map(|entry| entry.destination_relative_path.to_lowercase())
        .collect::<std::collections::BTreeSet<_>>()
        .len()
        == first.entries.len();
    let collision_detection_elapsed_us = collision_start.elapsed().as_micros();
    let resume_start = Instant::now();
    let verified = first
        .entries
        .iter()
        .step_by(2)
        .map(|entry| entry.destination_relative_path.as_str())
        .collect::<std::collections::BTreeSet<_>>();
    let skipped = first
        .entries
        .iter()
        .filter(|entry| verified.contains(entry.destination_relative_path.as_str()))
        .count();
    assert_eq!(skipped, first.entries.len().div_ceil(2));
    let resume_lookup_elapsed_us = resume_start.elapsed().as_micros();
    let second = build_manifest(&input).expect("generated fixture valid again");
    Scale {
        record_count: count,
        generated_selection_count: first.selected_file_count,
        planning_elapsed_us,
        estimated_input_lower_bound_bytes: estimate,
        manifest_checksum_stable: first.checksum == second.checksum,
        unique_destination_paths,
        collision_detection_elapsed_us,
        resume_lookup_elapsed_us,
    }
}

fn input(count: usize) -> ManifestBuildInput {
    ManifestBuildInput {
        plan_id: "generated-plan".into(),
        project_id: "generated-project".into(),
        project_name: "Generated Project".into(),
        plan_type: ProductionPlanType::ClientDelivery,
        selection_rules: SelectionRules::client_delivery(),
        organization: OrganizationStrategy::SingleFolder,
        filename_strategy: FilenameStrategy::ProjectSequence,
        overrides: vec![],
        virtual_collection_asset_ids: None,
        assets: (0..count)
            .map(|index| DeliveryAssetCandidate {
                asset_id: format!("asset-{index:06}"),
                original_filename: format!("DSC_{index:06}.ARW"),
                extension: Some("ARW".into()),
                byte_size: 8 * 1024 * 1024,
                captured_at: Some(format!(
                    "2026-08-12T10:{:02}:{:02}Z",
                    (index / 60) % 60,
                    index % 60
                )),
                camera: Some("Generated Camera".into()),
                human_decision: Some("keep".into()),
                rating: 0,
                starred: false,
                moment: None,
                sources: vec![DeliverySourceCandidate {
                    file_instance_id: format!("instance-{index:06}"),
                    source_root_id: Some("generated-root".into()),
                    relative_path: format!("camera/DSC_{index:06}.ARW"),
                    available: true,
                    verified: true,
                    observed_at: "2026-08-12T10:00:00Z".into(),
                    byte_size: 8 * 1024 * 1024,
                    content_checksum: Some(format!("checksum-{index:06}")),
                }],
            })
            .collect(),
    }
}

fn measure_copy() -> CopyMeasurement {
    let directory = tempfile::tempdir().expect("temporary benchmark folder");
    let source = directory.path().join("generated-source.bin");
    let destination = directory.path().join("delivery");
    fs::create_dir(&destination).expect("destination created");
    let bytes = vec![0x5A; 2 * 1024 * 1024];
    fs::write(&source, &bytes).expect("generated source written");
    let final_path = destination.join("Generated_0001.bin");
    let initial_copy_verified = matches!(
        copy_and_verify(&source, &destination, &final_path, || false, |_| {}).expect("copy succeeds"),
        CopyVerificationOutcome::Verified(result) if !result.reused_existing
    );
    let rerun_reused_existing_verified_copy = matches!(
        copy_and_verify(&source, &destination, &final_path, || false, |_| {}).expect("repeat succeeds"),
        CopyVerificationOutcome::Verified(result) if result.reused_existing
    );
    CopyMeasurement {
        generated_source_bytes: bytes.len(),
        initial_copy_verified,
        rerun_reused_existing_verified_copy,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_manifest_is_stable_and_unique() {
        let first = build_manifest(&input(100)).unwrap();
        let second = build_manifest(&input(100)).unwrap();
        assert_eq!(first.checksum, second.checksum);
        assert_eq!(first.entries.len(), 100);
    }
}
